[server]
BaseURL=https://gptlocal.MyCompany.com
ChatCompletions=/chat/completions
Completions=/completions
Embeddings=/embeddings
ImagesGenerations=/images/generations
Models=/models
AuthTokenEndpoint=/auth/token

[auth]
; Method can be Basic or Bearer
Method=Bearer
WindowsUser=DOMAIN\service_account
WindowsPassword=YourServiceAccountPassword
; If Method=Bearer, put your token here (SSO token or permanent token)
Token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[tls]
; Download the CA bundle and place it with your EXE or give full path:
CABundle=ca-bundle.crt
VerifyPeer=true

[client]
Model=gpt-5.3-chat
TimeoutMS=120000
Temperature=0.7
MaxTokens=2048
Stream=false